### ISSUE TITLE
npm install -d error: destination path `ng-cordova` already exists

### ISSUE THREAD

**Issue by felquis** [IonicBrazil/ionic-garden#29]
If I run `npm install -d` twice, it will cause an error:

![image](https://cloud.githubusercontent.com/assets/736728/8370887/3ea54912-1ba5-11e5-9877-d567a28b89db.png)

**Comment by giorgiofellipe** [comment]
@felquis What do you think is better? 
if already exists
- keep as it is
- update `git pull`
- anything else

**Comment by felquis** [comment]
I think we should remove `gulp install-source-module` from `postinstall`. Then we could pull if it already exist.

**Comment by giorgiofellipe** [comment]
@felquis we've added this to `postintall` again, so I'll fix it by checking if there's already a folder, if true I'll try to do a pull
