### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by f0ntana** [IonicBrazil/ionic-garden#36]
Let's go start install and i copy the error:

Clone:
git clone git@github.com:felquis/ionic-garden
Cloning into 'ionic-garden'...
remote: Counting objects: 771, done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 771 (delta 23), reused 0 (delta 0), pack-reused 701
Receiving objects: 100% (771/771), 1.90 MiB | 431.00 KiB/s, done.
Resolving deltas: 100% (327/327), done.
Checking connectivity... done.

Install dependencies:
sudo npm install -d
npm info ok 

Run the project on your browser:
ionic serve

ERROR:

Gulp startup tasks: [ 'styles', 'source', 'watch' ]
Running live reload server: http://localhost:35729
Watching : [ 'www/**/*', '!www/lib/**/*' ]
Running dev server: http://localhost:8100
Ionic server commands, enter:
  restart or r to restart the client app from the root
  goto or g and a url to have the app navigate to the given url
  consolelogs or c to enable/disable console log output
  serverlogs or s to enable/disable server log output
  quit or q to shutdown the server and exit

ionic $ [15:54:19] Using gulpfile ~/Developer/mobile/garden/ionic-garden/gulpfile.js
[15:54:19] Starting 'styles'...
[15:54:19] Starting 'source'...
[15:54:19] Starting 'watch'...
[15:54:19] Finished 'watch' after 54 ms
[15:54:19] Plumber found unhandled error:
 Error in plugin 'gulp-sass'
Message:
    src/scss/main.scss
  22:9  file to import not found or unreadable: ../lib/ionic/scss/ionic
Current dir: 
Details:
    column: 9
    line: 22
    file: stdin
    status: 1
    messageFormatted: src/scss/main.scss
  22:9  file to import not found or unreadable: ../lib/ionic/scss/ionic
Current dir: 
[15:54:19] Finished 'source' after 177 ms
[15:54:20] Starting 'source'...
Drops the bass -> gulp watch
Watching Ionic source
[15:54:20] Finished 'source' after 62 ms
[15:54:20] Starting 'source'...
[15:54:20] Finished 'source' after 73 ms

At browser:

Error: ENOENT: no such file or directory, open '/Users/fontana/Developer/mobile/garden/ionic-garden/www/index.html'

**Comment by felquis** [comment]
Pelo o que conversamos, entendi que o `modules/ionic` ficava vazio, adicionei o `bower install && gulp install-source-modules` no `postinstall`.

Verifica se o erro continua por favor?

**Comment by f0ntana** [comment]
@felquis sorry i dont understand this language

**Comment by felquis** [comment]
Here you go -> http://chocoballs.tumblr.com/post/45201917617

**Comment by felquis** [comment]
@f0ntana @giorgiofellipe Fechamos essa issue ou não?

**Comment by f0ntana** [comment]
Ainda não vou verificar ainda o que faço pois no meu não rolo depois posto
Em 03/07/2015 18:44, "Felquis Gimenes" <notifications@github.com> escreveu:
