### ISSUE TITLE
Best way to use $ionicModal

### ISSUE THREAD

**Issue by alvarowolfx** [IonicBrazil/ionic-garden#39]
As initially discussed on #31, when I was applying the controllerAs syntax from the [style guide](https://github.com/johnpapa/angular-styleguide#style-y030), I didn't liked this solution to pass $scope to the modal using the ```viewModel``` pattern. The problem is that the ionicModal don't have the controllerAs or a scopeAs option.

[Here](https://github.com/IonicBrazil/ionic-garden/blob/master/src/states/sidemenu/controller.js#L31) you can see the situation.

I need to test it better, but it seems that is creating a cycle on scope and view Model. I think I'll post a issue on Ionic to open the controllerAs/scopeAs possibility.

Any good idea ? Should I just pass $scope in this case ?

**Comment by giorgiofellipe** [comment]
There's no workaround, you're right doing this atm.
We only need to care and don't mess up the code binding something else to `$scope`.

I've found [this](http://forum.ionicframework.com/t/using-this-as-scope-when-creating-ionicmodal/9714) and they said the same.

**Comment by alvarowolfx** [comment]
So can we consider this issue closed @giorgiofellipe ? I just opened this to decide what should we use as a good example of using ionicModal.

**Comment by giorgiofellipe** [comment]
Yep!
